# Set the base image to use for subsequent instructions.
FROM python:3.11-alpine

# Set the working directory in the container.
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app.
# Copy the requirements.txt file into the container at /usr/src/app

COPY . .

# Update the package list
RUN apk update && apk add --no-cache wget

# Install any needed packages specified in requirements.txt.
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the application.
CMD ["python", "main.py"]
